export const CATEGORIES = [
  "income",
  "food",
  "groceries",
  "transport",
  "housing",
  "utilities",
  "healthcare",
  "education",
  "shopping",
  "entertainment",
  "subscriptions",
  "debt_payment",
  "savings",
  "other",
] as const;
